find_library(MATH_LIBRARY NAMES m libm)
find_path(MATH_INCLUDE_DIR math.h)
set(MATH_LIBRARIES ${MATH_LIBRARY})
set(MATH_INCLUDE_DIRS ${MATH_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Math REQUIRED_VARS
	MATH_LIBRARIES
	MATH_INCLUDE_DIRS)
	
mark_as_advanced(MATH_LIBRARY MATH_INCLUDE_DIR)