find_library(SDL2_LIBRARY NAMES SDL2 libSDL2)
find_path(SDL2_INCLUDE_DIR SDL2/SDL.h)
set(SDL2_LIBRARIES ${SDL2_LIBRARY})
if(SDL2_INCLUDE_DIR)
  set(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR}/SDL2)
endif()

if(WIN32)
  find_library(SDL2_MAIN_LIBRARY NAMES SDL2main libSDL2main)
  set(SDL2_LIBRARIES ${SDL2_MAIN_LIBRARY};${SDL2_LIBRARIES})
endif()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 REQUIRED_VARS
	SDL2_LIBRARIES
	SDL2_INCLUDE_DIRS)
	
mark_as_advanced(SDL2_LIBRARY SDL2_INCLUDE_DIR SDL2_MAIN_LIBRARY)