#  Makefile 
#  Auteur : Farès BELHADJ
#  Email  : amsi@ai.univ-paris8.fr
#  Date   : 12/12/2014

default: 
	@$(MAKE) -C example01
	@$(MAKE) -C example02
	@$(MAKE) -C example03

clean:
	@$(MAKE) -C example01 clean
	@$(MAKE) -C example02 clean
	@$(MAKE) -C example03 clean

